[package]
name = "asyncnal"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = { version = "1.7.1", features = ["weak"] }
intrusive-collections = "0.9.7"
tokio = "1.45.1"

[dev-dependencies]
tokio = { version = "1.45.1", features = ["full"] }
